folders:
  # input defaults to the whole package directory
  input: ./src
  # output defaults to a folder called build. This can be set individually in package.json (see below)
  output: dist
enableBetaFeatures:
  # folderConfiguration defaults to true
  # setting a default input/output folder as shown above
  # and per package i/o folder in package.json as below
  # "yarn.build": {
  #   "input": "src",
  #   "output": "dist"
  # },
  folderConfiguration: true
  # To enable yarn build path/to/package
  targetedBuilds: true
